FE-AgentGuard/FE-AgentGuard/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FE_AgentGuard.Data;
using FE_AgentGuard.Models.Models;
using FE_AgentGuard.ServerHandling;

namespace FE_AgentGuard.Controllers
{
    public class AgentsController : Controller
    {
        private readonly HttpClient httpClient;
        private readonly string UrlBase;
        AgentServer server ;

        public AgentsController(HttpClient HttpClient)
        {
            UrlBase = "http://localhost:5149/Agents";
            httpClient = HttpClient;
            server = new(httpClient, UrlBase);
        }

        // GET: Agents
        public async Task<IActionResult> Index()
        {
            
            return View(await server.GetObjectsAsync());
        }

        // GET: Agents/Details/5
        public async Task<IActionResult> Details(int id)
        {
            AgentServer server = new(httpClient, UrlBase);
            Agent agent = await server.GetObjectAsync(id);
            return View(agent);
        }
    }
}

FE-AgentGuard/FE-AgentGuard/Controllers/GeneralController.cs
using FE_AgentGuard.InterFaces;
using FE_AgentGuard.Models.Models;
using FE_AgentGuard.Models.ServerModel;
using FE_AgentGuard.Models.ViewModel;
using FE_AgentGuard.ServerHandling;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;

namespace FE_AgentGuard.Controllers
{
    public class GeneralController : Controller
    {
        // GET: GeneralController1
        private readonly HttpClient httpClient;
        private readonly string urlAgent;
        private readonly string urlTarget;
        private readonly string urlMission;
        private TokenService tokenService;

        public GeneralController(HttpClient HttpClient)
        {
            httpClient = HttpClient;
            urlAgent = "http://localhost:5149/Agents";
            urlTarget = "http://localhost:5149/Targets";
            urlMission = "http://localhost:5149/missions";
        }

        public async Task<ActionResult> GeneralView()
        {

            AgentServer AgentServer = new(httpClient, urlAgent);
            TargetServer TargetServer = new(httpClient, urlTarget);
            MissionServer MissionServer = new(httpClient, urlTarget);
            Task<List<Agent>> taskAgents = AgentServer.GetObjectsAsync();
            Task<List<Target>> taskTargets = TargetServer.GetObjectsAsync();
            Task<List<Mission>> taskMission = MissionServer.GetObjectsAsync();

            List<Agent> agents = await taskAgents;
            List<Target> targets = await taskTargets;
            List<Mission> missions = await taskMission;

            List<Person> persons = agents.Cast<Person>()
                                        .Concat(targets.Cast<Person>())
                                        .ToList();
            Dictionary<Point, Person> dict = new Dictionary<Point, Person>();
            foreach (var person in persons)
            {
                person.color = changeColor(person,missions);
                dict[person.Point] = person;
            }
            General general = new(dict, targets, missions, agents);

            return View(general);
        }

        public async Task<ActionResult> Details(int id)
        {
            PersonServer server = new(httpClient, urlAgent);
            Person person = await server.GetObjectAsync(id);
            return View(person);
        }


        public string changeColor(Person person,List<Mission> mission
            )
        {
            if(person is Agent)
            {
                if (person.is_active) { return "yellow"; }
                return "blue";
            }
            if (TargetAssigned(person.Id,mission)) { return "green"; }
            return "red";
        }
        private bool TargetAssigned(int id, List<Mission> missions)
        {
            foreach (var mission in missions)
            {
                if (mission.targetID == id) {  return true; }
            }
            return false;
        }
    }
}

FE-AgentGuard/FE-AgentGuard/Controllers/MissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FE_AgentGuard.Data;
using FE_AgentGuard.Models.Models;
using FE_AgentGuard.ServerHandling;
using BE_AgentGuard.Enums;
using FE_AgentGuard.Models.ServerModel;

namespace FE_AgentGuard.Controllers
{
    public class MissionsController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly string _url;
        private readonly MissionServer server;
        private TokenService tokenService;

        public MissionsController(HttpClient httpClient, TokenService tokenService)
        {
            _httpClient = httpClient;
            _url = "http://localhost:5149/missions";
            server = new(_httpClient, _url);
            this.tokenService = tokenService;
        }
        public async Task<IActionResult> Index()
        {
            //var fE_AgentGuardContext = _context.Mission.Include(m => m.Agent).Include(m => m.Target);
            MissionServer server = new(_httpClient, _url);
            return View(await server.GetObjectsAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var mission = await _context.Mission
            //    .Include(m => m.Agent)
            //    .Include(m => m.Target)
            //    .FirstOrDefaultAsync(m => m.Id == id);
            MissionServer server = new(_httpClient, _url);
            Mission mission = await server.GetObjectAsync(id);
            if (mission == null)
            {
                return NotFound();
            }

            return View(mission);
        }
        //https://localhost:7254/Missions/assigned/1
        [HttpPost("missions/assigned/{id}")]
        public async Task<IActionResult> assigned(int id)
        {
            string token = tokenService.Token.token;
            StatusMission status = StatusMission.ASSIGNED;
            MissionAssigned mission = new(token, status);
            await server.UpdateObjectAsync(mission, id);
            return RedirectToAction("Index");
        }
    }
}

FE-AgentGuard/FE-AgentGuard/Controllers/TargetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FE_AgentGuard.Data;
using FE_AgentGuard.Models.Models;
using FE_AgentGuard.ServerHandling;
using System.Net.Http;
using System.Runtime.Intrinsics.Arm;

namespace FE_AgentGuard.Controllers
{
    public class TargetsController : Controller
    {
        private readonly HttpClient httpClient;
        private readonly string UrlBase;
        private readonly TargetServer server;

        public TargetsController(HttpClient HttpClient)
        {
            UrlBase = "http://localhost:5149/Targets";
            httpClient = HttpClient;
            server = new(httpClient, UrlBase);
        }

        public async Task<IActionResult> Index()
        {
            return View(await server.GetObjectsAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            Target agent = await server.GetObjectAsync(id);
            return View(agent);
        }


   
    }
}

FE-AgentGuard/FE-AgentGuard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    @{
        var currentPage = Context.Request.Path;
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @if (!currentPage.Equals("/Login/login") && !currentPage.Equals("/"))
    {
    <meta http-equiv="refresh" content="1"></meta>
    }
    <title>@ViewData["Title"] - FE_AgentGuard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FE_AgentGuard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FE_AgentGuard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="General" asp-action="GeneralView">תצוגה כללית</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agents" asp-action="index">תצוגת סוכנים</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Targets" asp-action="index">תצוגת מטרות</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success" asp-area="" asp-controller="Missions" asp-action="index">ציוות סוכנים</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            ניהול סוכנים <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>